-- Create database
CREATE DATABASE IF NOT EXISTS digital_library;
USE digital_library;

-- Users table
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100) UNIQUE,
  password VARCHAR(255),
  role ENUM('student', 'admin') DEFAULT 'student'
);

-- Seats table
CREATE TABLE seats (
  seat_number INT PRIMARY KEY,
  status ENUM('available', 'booked') DEFAULT 'available',
  booked_by INT DEFAULT NULL,
  booking_date DATE,
  FOREIGN KEY (booked_by) REFERENCES users(id)
);

-- Insert 60 seats
INSERT INTO seats (seat_number) VALUES 
(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),
(11),(12),(13),(14),(15),(16),(17),(18),(19),(20),
(21),(22),(23),(24),(25),(26),(27),(28),(29),(30),
(31),(32),(33),(34),(35),(36),(37),(38),(39),(40),
(41),(42),(43),(44),(45),(46),(47),(48),(49),(50),
(51),(52),(53),(54),(55),(56),(57),(58),(59),(60);

-- Create admin account (password is "admin123")
INSERT INTO users (name, email, password, role)
VALUES ('Admin', 'admin@library.com', 
'$2y$10$YvH/t0Chz8Zc1nqFTjP0LOffMl.zjzqQ.YH7/Ul6xqfFwY/RnAYjC', 'admin');
-- Password hash generated by: password_hash('admin123', PASSWORD_DEFAULT)
